server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/heima?useSSL=false
    username: root
    password: "0316"
    driver-class-name: com.mysql.jdbc.Driver
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    cn.itcast: debug
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo